---
# Patching Redhat
- name: Perfom patching on RedHat
  block:
    - name: patch - RedHat - Update all packages to their latest version
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: patch - RedHat - Remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.yum:
        autoremove: yes

  when: ansible_distribution == "RedHat"

# Patching Ubuntu
- name: Perfom patching on Ubuntu
  block:
    - name: patch - Ubuntu - Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: patch - Ubuntu - Remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.apt:
        autoremove: yes

  when: ansible_distribution == "Ubuntu"
  
