---
# Patching Redhat
- name: Perfom patching on RedHat
  when: ansible_distribution == "RedHat"
  block:
    - name: RedHat - Apply security updates
      ansible.builtin.yum:
        name: "*"
        state: latest
        security: true

    - name: RedHat - Remove dependencies that are no longer required
      ansible.builtin.yum:
        autoremove: true

# Patching Ubuntu
- name: Perfom patching on Ubuntu
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Ubuntu - Apply security updates
      ansible.builtin.apt:
        upgrade: dist

    - name: Ubuntu - Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
