---
- name: Patching of Linux boxes
  hosts: linux
  gather_facts: true
  become: true

  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        dir: group_vars

    - name: Import environment role
      ansible.builtin.import_role:
        name: environment

    - name: Import patching role
      ansible.builtin.import_role:
        name: patching

  post_tasks:
    - name: Debug the outcome
      ansible.builtin.debug:
        msg:
          - "{{ inventory_hostname }} packages updated successfully "
