---
# tasks file for roles/environment
- name: Print dates
  ansible.builtin.debug:
    msg:
      - "date : {{ ansible_date_time['date'] }}"
      - "time : {{ ansible_date_time['time'] }}"

- name: Debug distribution and version
  ansible.builtin.debug:
    msg:
      - "distribution : {{ ansible_distribution }}"
      - "distribution_major_version : {{ ansible_distribution_major_version }}"
